server:
  port:  ${PORT:9000}

spring:
  application:
    name: acc

  flyway:
    enabled: ${DB_MIGRATION:false}
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_DATABASE:MyAcc}
    username: ${DB_POLICY_USERNAME:MyUser}
    password: ${DB_POLICY_PASSWORD:MyPassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none